# MyBatis配置
mybatis:
  mapUnderscoreToCamelCase: true
  callSettersOnNulls: true
  # 搜索指定包别名
  typeAliasesPackage: com.baseAdmin.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  # mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
      log-impl:   org.apache.ibatis.logging.stdout.StdOutImpl
