spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        first:
           url:  jdbc:postgresql://192.168.111.250:5432/postgres
           username: user1
           password: user1
           druid.driver-class-name: org.postgresql.Driver
           #2.连接池配置
           #初始化连接池的连接数量 大小，最小，最大
           initial-size: 6
           min-idle: 6
           max-active: 21
           #配置获取连接等待超时的时间
           max-wait: 60000
           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
           time-between-eviction-runs-millis: 60000
           # 配置一个连接在池中最小生存的时间，单位是毫秒
           min-evictable-idle-time-millis: 30000
           # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
           pool-prepared-statements: true
           max-pool-prepared-statement-per-connection-size: 20
           #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
           filters: stat,wall
           filter:
             wall:
               enabled: true
             stat:
               enabled: true
               log-slow-sql: true  # 开启慢查询
               slow-sql-millis: 2000  # 多少秒算慢查询
           #3.基础监控配置
           web-stat-filter:
               enabled: true
               url-pattern: /*
               #设置不统计哪些URL
               exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
               session-stat-enable: true
               session-stat-max-count: 100
           stat-view-servlet: #配置监控页功能
               enabled: true
               # 数据监控访问路径
               url-pattern: /druid/*
               reset-enable: true
               #设置监控页面的登录名和密码
               login-username: admin
               login-password: 123
               #allow: 127.0.0.1,192.168.2.111  #IP白名单(没有配置或者为空，则允许所有访问)。允许谁访问druid后台，默认允许全部用户访问。
               #deny:  #IP黑名单 (存在共同时，deny优先于allow)。不允许谁访问druid后台
        second:
           url: jdbc:postgresql://192.168.111.250:5432/postgres
           username: postgres
           password: postgres
           druid.driver-class-name: org.postgresql.Driver
           #2.连接池配置
           #初始化连接池的连接数量 大小，最小，最大
           initial-size: 6
           min-idle: 6
           max-active: 21
           #配置获取连接等待超时的时间
           max-wait: 60000
           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
           time-between-eviction-runs-millis: 60000
           # 配置一个连接在池中最小生存的时间，单位是毫秒
           min-evictable-idle-time-millis: 30000
           # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
           pool-prepared-statements: true
           max-pool-prepared-statement-per-connection-size: 20
           #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
           filters: stat,wall
           filter:
             wall:
               enabled: true
             stat:
               enabled: true
               log-slow-sql: true  # 开启慢查询
               slow-sql-millis: 2000  # 多少秒算慢查询
           #3.基础监控配置
           web-stat-filter:
             enabled: true
             url-pattern: /*
             #设置不统计哪些URL
             exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
             session-stat-enable: true
             session-stat-max-count: 100
           stat-view-servlet: #配置监控页功能
             enabled: true
             # 数据监控访问路径
             url-pattern: /druid/*
             reset-enable: true
             #设置监控页面的登录名和密码
             login-username: admin
             login-password: 123
             #allow: 127.0.0.1,192.168.2.111  #IP白名单(没有配置或者为空，则允许所有访问)。允许谁访问druid后台，默认允许全部用户访问。
             #den