server:
  port: 9080
spring:
  profiles:
    active: datasource,mybatis,pageHelper
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    
     # 使用springboot自带的logback日志组件
logging:
    file: 
       # 日志保存路径
       name: d:/log/singleDS.log
    level:
     # 项目日志级别debug
     #root: info  debug
     # 包日志级别
      com:
         baseAdmin: debug 
 
