package com.baseAdmin.g.mapper;

import com.baseAdmin.g.pojo.T3;
import com.baseAdmin.g.pojo.T3Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T3Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	long countByExample(T3Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	int deleteByExample(T3Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	int insert(T3 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	int insertSelective(T3 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	List<T3> selectByExample(T3Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	T3 selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") T3 row, @Param("example") T3Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") T3 row, @Param("example") T3Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(T3 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t3
	 * @mbg.generated
	 */
	int updateByPrimaryKey(T3 row);
}