spring:
   datasource: 
      druid:
         second: 
            url:  jdbc:postgresql://127.0.0.1:5432/pg2
            username: postgres
            password: Pass1324
            druid.driver-class-name: org.postgresql.Driver
            #2.连接池配置
            #初始化连接池的连接数量 大小，最小，最大
            initial-size: 6
            min-idle: 6
            max-active: 21
            #配置获取连接等待超时的时间
            max-wait: 60000
            #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            time-between-eviction-runs-millis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 30000
            # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            filters: stat,wall
            filter:
              wall:
                enabled: true
              stat:
                enabled: true
                log-slow-sql: true  # 开启慢查询
                slow-sql-millis: 2000  # 多少秒算慢查询